### ISSUE TITLE
CanBeExploded() does not seem to have an entry for the Tulip Launcher

### ISSUE THREAD

**Issue by T-SquaredProductions** [smitelli/cosmore#1]
I need to be able to make this actor unaffected by explosions, but the source code doesn't seem to have an entry in the CanBeExploded() list for the Tulip Launcher. Also, I don't see a case argument to make Cosmo go in front of an actor, or change the layering for an actor.

Other than that, because of how the commands are organized, making some of the custom elements is going pretty well!

**Comment by smitelli** [comment]
Tulip launchers behave specially around explosions. (They need to be hit twice, they flash white while in pain, and they spawn blue parachute ball shards upon destruction.) Because of the different behavior, all this happens inside the tick function, [ActTulipLauncher()](https://github.com/smitelli/cosmore/blob/03aedb83113d31cfefc5a79fd9ab21439bd54043/src/game1.c#L5165), and not in `CanBeExploded()`.

Sprite draw order is constrained by the order of function calls in [GameLoop()](https://github.com/smitelli/cosmore/blob/03aedb83113d31cfefc5a79fd9ab21439bd54043/src/game1.c#L9760-L9763). `DrawPlayerHelper()` is called first, then `MoveAndDrawActors()` happens, which means _all_ actors overdraw the player. Within the actors themselves, they are drawn in `actors[]` array order, later ones overdrawing earlier ones.

I haven't really explored how the game behaves with player/actor function calls rearranged, but those would be the places to look. Giving actors any sense of z-layering or priority would involve adding a new member to the `Actor` struct and sorting them during `MoveAndDrawActors()`. Not impossible, but the original authors included no provisions for that.

**Comment by T-SquaredProductions** [comment]
Thanks for the help. I actually seem to have found out how to comment out the code that makes the tulip game object vulnerable to bombs.
